"""test

Revision ID: 12c0502243d0
Revises: 
Create Date: 2025-03-01 05:16:10.502135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c0502243d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_message', sa.VARCHAR(length=500), nullable=False),
    sa.Column('translated_message', sa.VARCHAR(length=500), nullable=True),
    sa.Column('response', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
